let transactions=  {
    "1": {
        "from": "2AqruPK4zjhRprsGx6eNDQ3e35RN",
            "to": "CGGPCQJmtF5CmMH7GBgmGAWHeqL",
            "amount": "10",
            "fee": "500000",
            "timestamp": "1638785082",
            "data": "jivPpAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACBiZGNmMjk1ZTNmMzA0ZWY5YWIwMmZiMDc0MTE2MjBlYgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAZWNjMzUzYjc4MTIzM2I5YjI5ZmQwYTZjOWZkOTIwZjZhOGRjZjY4NzYwYmI3Yjc2Y2Q3MDAzN2RjYWRkYzhjOGY0MGJjNTc3ODFkODMzNjJlOTJlYTc4MWNlYTk2YmIwZmY3MTI5ODk5NDM1MmIwZGFjYzU1MGU1YTQ1NGYzNzU=",
            "sign": "/nraUwUd9/d45X5StAKkwqztUyc+tVXavsx0pWyBygZP/e1cFToB9hDuLOCgRkdUSDNXw9BkjdQXf9LYo5UwPAA=",
            "hash": "PXN4OQuUobZYZeHd7lOxRZocWBQEaPcZvY1TT7lUIQE="
    },
    "2": {
        "from": "4NJZqBjYm14isZMxSAHWYiWn1Sga",
            "to": "CGGPCQJmtF5CmMH7GBgmGAWHeqL",
            "amount": "10",
            "fee": "500000",
            "timestamp": "1638785082",
            "data": "jivPpAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACBiZGNmMjk1ZTNmMzA0ZWY5YWIwMmZiMDc0MTE2MjBlYgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAZWNjMzUzYjc4MTIzM2I5YjI5ZmQwYTZjOWZkOTIwZjZhOGRjZjY4NzYwYmI3Yjc2Y2Q3MDAzN2RjYWRkYzhjOGY0MGJjNTc3ODFkODMzNjJlOTJlYTc4MWNlYTk2YmIwZmY3MTI5ODk5NDM1MmIwZGFjYzU1MGU1YTQ1NGYzNzU=",
            "sign": "ZqkpkqntYbvcXjWd8T028dlUKxQbriEAn2vPQGsdOXIK/AGnVqFsJNkpKZhZVLtjPtsNhreTjFoHK/97kMMm5QE=",
            "hash": "3bAyl7A55eo79Qz6+CjEdF6LTmASx7WnE7bysITB0+o="
    }
}


Object.keys(transactions).forEach((function (key) {
    if (!key) {
        return
    }
    transactions[key].txHash = transactions[key].hash
    console.log(transactions[key].hash)
}))

console.log(transactions)